apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sgtn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-sgtn@sha256:c48a12302f4d771ca12f33157cdd002ac0279471d50493c01b51247bcdd16194
        name: my-nodejs
        resources: {}
status: {}
